#!/bin/bash

# Aggiorna l'indice dei pacchetti e installa python3 e pip3
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y python3 python3-pip

# Installa pacchetti Python comuni
pip3 install numpy pandas matplotlib seaborn scikit-learn minisom scikit-metrics jupyter

# Aggiungi il kernel Python al notebook di Jupyter
python3 -m ipykernel install --user --name=python3

# Opzionale: aggiornamento di pip
pip3 install --upgrade pip

echo "Installazione completata!"
